-- phpMyAdmin SQL Dump
-- version 4.6.6deb5
-- https://www.phpmyadmin.net/
--
-- Client :  localhost:3306
-- Généré le :  Jeu 10 Janvier 2019 à 11:14
-- Version du serveur :  5.7.24-0ubuntu0.18.04.1
-- Version de PHP :  7.2.10-0ubuntu0.18.04.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `Loire_en_Vert`
--

-- --------------------------------------------------------

--
-- Structure de la table `eventLoire`
--

CREATE TABLE `eventLoire` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `event_date_start` date NOT NULL,
  `event_date_finish` date NOT NULL,
  `event_time` varchar(255) DEFAULT NULL,
  `event_where` varchar(255) NOT NULL,
  `place` varchar(255) NOT NULL,
  `city` varchar(255) DEFAULT NULL,
  `who` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  `free` varchar(255) NOT NULL,
  `urlSite` varchar(255) DEFAULT NULL,
  `description` varchar(50000) NOT NULL,
  `lat` decimal(10,6) NOT NULL,
  `lng` decimal(10,6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Contenu de la table `eventLoire`
--

INSERT INTO `eventLoire` (`id`, `name`, `image`, `event_date_start`, `event_date_finish`, `event_time`, `event_where`, `place`, `city`, `who`, `type`, `free`, `urlSite`, `description`, `lat`, `lng`) VALUES
(7, 'La mer et son immensité', 'http://fonds-ecran.widewallpapershd.info/file/28384/728x410/16:9/%C3%89t%C3%A9-plage-bord-de-la-mer-paradis-tropical_1634096795.jpg', '2019-02-01', '2019-02-28', '9 h 00 - 18 h 00', 'Stéphanois-Pilat', 'Maison de la Nature', 'Saint-Etienne', 'Famille', 'expositions', 'true', 'https://loireenvert.fr/events/la-mer-et-son-immensite-fevrier/', 'Hissez les voiles et prenez le large…\r\n\r\nLa mer… Elle fait partie de la vie de chacun : en vacances, en voyage, lors d’activités sportives\r\nou encore par l’intermédiaire de quantités de produits que nous consommons. Mais connaissons-nous vraiment cette immensité et tous les trésors qu’elle recèle ? Quel rôle joue-t-elle sur notre planète ? Pouvons-nous vraiment l’apprivoiser comme nous le pensons ?\r\n\r\nPlus qu’un enjeu de société, les mers se dépeuplent, s’épuisent et sont dans des situations alarmantes. La réaction à protéger et conserver nos milieux marins n’est pas une solution, c’est une obligation.\r\n\r\nSans inscription\r\nGratuit\r\n\r\nOuverture :\r\nDu lundi au vendredi de 9 h à 18 h', '45.420986', '4.385753'),
(8, 'Les poissons migrateurs', 'https://biosphere-bassin-dordogne.fr/wp-content/uploads/2018/08/Saumon-atlantique-%C2%A9-Hans-Petter-Fjeld.jpg', '2018-12-01', '2018-12-31', '13 h 30 - 18 h 00', 'Forez', 'Ecopôle du Forez', 'null', 'Public en situation de handicap', 'exposition', 'false', NULL, 'L’exposition itinérante « Grands Migrateurs de Loire » créée par LOGRAMI dans le cadre du Plan Loire Grandeur Nature présente les poissons migrateurs du bassin de la Loire et leur gestion. L’objectif est de sensibiliser le plus grand nombre aux poissons migrateurs, à leurs problématiques ainsi qu’à l’état des populations sur la Loire.', '45.744839', '4.825602'),
(9, 'L’Afrique noire et ses symboles', 'https://s-media-cache-ak0.pinimg.com/originals/ef/7e/54/ef7e54f3cddc6348136c0ab123e571ca.jpg', '2019-02-01', '2019-02-28', '14 h 00 - 18 h 0', 'Stéphanois-Pilat', 'Maison de la Réserve', 'null', 'Public en situation de handicap', 'exposition', 'true', NULL, 'Du légendaire désert du Sahara aux méandres du Congo, du majestueux  massif de l’Atlas aux neiges éternelles du Kilimandjaro, le continent africain révèle un patrimoine sans égal. Partez à la découverte de ce vaste continent contrasté qu’est l’Afrique. Il y sera question de ses habitants, de leurs coutumes, de sa faune et de sa flore mais aussi des maux qui la tourmentent. Parler de l’Afrique c’est également aborder sa culture ancestrale, son patrimoine oral et ses contes, ainsi que les grands écrivains qu’elle a vu naître.', '45.457562', '4.263197'),
(11, 'La biodiversité et les corridors biologiques', 'https://www.reforestaction.com/sites/default/files/field/image/corridor-biologique.jpg', '2019-02-01', '2019-02-28', '13 h 30 - 18 h 00', 'Forez', 'Ecopôle du Forez', 'null', 'Public en situation de handicap', 'Expositions', 'false', 'https://loireenvert.fr/events/la-biodiversite-et-les-corridors-biologiques/', 'La biodiversité, ou diversité biologique, constitue le tissu vivant de la planète. Elle recouvre l’ensemble des formes de vie sur Terre, les relations qui existent entre elles et avec leurs milieux depuis l’origine commune de la vie. Un ensemble de panneaux vous présenteront la biodiversité sur le territoire de Saint-Etienne La Métropole et les actions menées en faveur des corridors biologiques.\r\n\r\nSans inscription\r\n\r\nOuverture :\r\nMercredis,samedis, dimanches et tous les jours des vacances scolaires de 13 h 30 à 18 h.\r\n\r\nTarif :\r\nPlein tarif : 3 €\r\nTarif réduit* : 1,60 €\r\n*Tarif réduit : demandeurs d’emploi, étudiants, enfants de 7 à 14 ans sur justificatif\r\nGratuit (sur justificatif) : enfants de moins de 7 ans, adhérents de la FNE Loire et de ses associations membres', '45.689464', '4.197532'),
(12, 'Abritons les insectes', 'https://media.cooperation.ch/images/2015/06/15/main_1046x570_1533584537583.jpg', '2019-01-23', '2019-01-23', '14 h 00 - 16 h 00', 'Stéphanois-Pilat', 'Réserve Naturelle Régionale des gorges de la Loire', 'null', 'Enfants', 'Ateliers', 'false', 'https://loireenvert.fr/events/abritons-les-insectes/', 'Préparons d’ores et déjà l’arrivée du printemps et aménageons une maison pour les insectes que nous installerons dans notre jardin.\r\n\r\nDès 4 ans\r\nSur inscription (de 5 à 20 places) jusqu’au 23 janvier 12 h.\r\nTarif \r\nAdultes accompagnant : 3 €\r\nEnfants (7-14 ans) : 2 €\r\nGratuit moins de 7 ans', '45.457562', '4.263197'),
(13, 'Construis ton nichoir', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Birdhouse_aka.jpg/1200px-Birdhouse_aka.jpg', '2019-02-19', '2019-02-19', '14 h 30 - 16 h 30', 'Forez', 'Ecopôle du Forez', 'null', 'Enfants', 'Ateliers', 'false', 'https://loireenvert.fr/events/construis-ton-nichoir-18-fevrier/', 'Après avoir parcouru le sentier de l’Ecopôle du Forez pour retrouver les différents nichoirs et ses espèces occupantes, tu construiras un nichoir de tes propres mains et tu repartiras avec pour l’installer chez toi.\r\n\r\nA partir de 6 ans\r\nLes enfants doivent être accompagnés d’un adulte.\r\nSur inscription (de 5 à 15 places) jusqu’au vendredi 15 février 12h.\r\n\r\nPrévoir : tenue confortable, vêtements chauds.\r\n\r\nTarif (comprend le coût du nichoir)\r\nEnfant : 10 €\r\nAdulte accompagnant : 5 €', '45.689464', '4.197532'),
(14, 'Croq’ Paysage', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM72XN6HdIcNGP5_Z0rmpuk2vzPNG9sp70UQ1DXpilFta79r_2gQ', '2019-02-27', '2019-02-27', '14 h 00 - 16 h 00', 'Stéphanois-Pilat', 'Réserve Naturelle Régionale des gorges de la Loire', 'null', 'Enfants', 'Sorties découvertes', 'false', 'https://loireenvert.fr/events/croq-paysage-2019-02-27/', 'Depuis le point de vue surplombant les gorges de la Loire, observons le paysage qui nous entoure et tentons d’y déceler les marques du passé. Tantôt façonné par le fleuve, tantôt par l’homme, découvrons l’histoire de ce site.\r\n\r\nSur inscription (de 5 à 25 places) jusqu’au 27 février midi\r\nAnimation annulée si moins de 5 inscrits ou,en cas de mauvais temps. Vous serez remboursé.\r\nEnfants bienvenus dès 6 ans.\r\nLes enfants doivent être accompagnés d’un adulte.\r\n\r\nTarif\r\nAdulte : 3 €\r\nEnfant de 7 à 14 ans : 2 €*\r\nEnfant de moins de 7 ans : gratuit*\r\n*Sur justificatif', '45.457562', '4.263197'),
(15, 'L’anniversaire d’Annie la fourmi', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBGGa5ks4XggZhSqyCYD25RcmKcmW8gYZe47FR83nbOLnxYYDEIQ', '2019-04-15', '2019-04-15', '14 h 30 - 16 h 00', 'Forez', 'Ecopôle du Forez', 'null', 'Enfants', 'Ateliers', 'false', 'https://loireenvert.fr/events/annie-la-fourmi-2019-04-15/', 'Pour les enfants : Viens aider l’équipe de l’Ecopôle à organiser l’anniversaire d’Annie la fourmi. Tu découvriras tous ses amis autour d’une fête surprise !\r\n\r\nA partir de 4 ans\r\n\r\nLes enfants doivent être accompagnés d’un adulte.\r\n\r\nSur inscription jusqu’au: 15 avril 12 h (de 5 à 15 places)\r\n\r\nMerci d’inscrire le nombre exact de participants (adultes et enfants)\r\nAnimation annulée si moins de 5 inscrits. Vous serez remboursé.\r\n\r\nTarif : \r\nAdulte : 5 €\r\nEnfant : 2,50 €', '45.689464', '4.197532'),
(16, 'Marche des Papillottes\r\n', 'https://www.lamontagne.fr/photoSRC/Gw--/marche-pour-la-foret-a-neoux_4037388.jpeg', '2018-12-16', '2018-12-16', 'Toute la journée', 'Roannais', 'Maison des sociétés', 'null', 'Passionnés', 'Randonnées', 'false', 'https://loireenvert.fr/events/marche-des-papillottes/', 'Rando-campagnarde® FFRandonnée (réduction aux licenciés)\r\nRiorges (Roannais) : marche des papillottes.\r\n5 circuits de 6 à 29 km\r\nPlus d’infos sur  http://rando-loire.org\r\nConsultez la rubrique « Prochaines randos » : détails sur cette rando, numéro de téléphone, etc.', '46.043148', '4.033294'),
(18, 'Balade découverte à l’Ecopôle du Forez', 'https://cdn-s-www.leprogres.fr/images/80B1C0F5-3C65-41D6-93B9-11F74B81B2E7/LPR_v1_02/balade-crepusculaire-a-l-ecopole-du-forez-a-la-decouverte-de-la-faune-et-de-la-flore-ici-un-heron-cendre-photo-celik-erkul-1479278308.jpg', '2019-10-06', '2019-10-06', '14 h 30 - 16 h 00', 'Forez', 'Ecopôle du Forez', 'null', 'Famille', 'Passionnés', 'false', 'https://loireenvert.fr/events/balade-decouverte-a-lecopole-du-forez-2019-10-06/', 'Venez découvrir l’Ecopôle du Forez en compagnie d’un guide naturaliste de la Ligue pour la protection des oiseaux de la Loire.\r\n\r\nAu cours d’une balade commentée d’environ 1 h 30, vous observerez une multitude d’oiseaux d’eau et comprendrez l’histoire du site qui les a conduit à s’installer ici.\r\n\r\nSans inscription (de 5 à 15 places)\r\n\r\nTarif\r\nPlein tarif : 5 €\r\nTarif réduit* : 2,50 €\r\nGratuit : adhérents LPO et enfants de moins de 7 ans sur justificatif\r\n* Tarif réduit : demandeurs d’emploi, étudiants, enfants de 7 à 14 ans, adhérents de FNE Loire et de ses associations membres', '45.689464', '4.197532'),
(19, 'Fête du sol et de la terre', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPGSl9A7Y5xf5Wz6uxpzWYOFu0_u2gswAdTvRo_-mr6qsFyh3ITg', '2019-03-17', '2019-03-17', '10 h 00 - 18 h 00', 'Forez', 'Ecopôle du Forez', 'null', 'Famille', 'Evénements', 'false', 'https://loireenvert.fr/events/fete-du-sol-terre/', 'Dans le cadre de la journée internationale de la forêt (21 mars), venez fêter avec nous un arbre commun des bords de Loire que nous utilisons tous sous différentes formes depuis des millénaires.\r\n\r\nProgramme\r\nTressage de saule vivant,\r\nInitiation à la vannerie,\r\nExpo-vente de maîtres vanniers,\r\nBalade nature,\r\nAteliers enfants,\r\nConstruction de nichoirs\r\n\r\nSans inscription\r\n\r\nTarif \r\n1€ par personne (adulte ou enfant)', '45.689464', '4.197532'),
(20, 'Visite guidée de la réserve naturelle des gorges de la Loire', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgjGWTaQrx7Vi2CMZIk4X9cU80rTanpEVbIyVTwVGKeMSv4FWPjw', '2019-02-11', '2019-02-11', '14:30 - 16:30', 'Stéphanois-Pilat', 'Gorges de la Loire', 'null', 'Famille', 'Sorties découvertes', 'true', 'https://loireenvert.fr/events/visite-guidee-de-reserve-naturelle-gorges-de-loire-2018-02-11/', 'Lors d’une balade commentée, venez découvrir un site naturel exceptionnel et protégé depuis 1988 sous la forme d’une réserve naturelle.\r\n\r\nSa mosaïque de milieux naturels et sa richesse faunistique et floristique sont protégés par la FRAPNA Loire et le SMAGL depuis 2012.\r\n\r\nAu départ de la Maison de la Réserve, votre guide vous emmènera aux deux points de vue les plus connus de la réserve, avec vue plongeante sur les gorges de la Loire !\r\n\r\nLaissez-vous raconter de manière interactive l’histoire du site, son patrimoine naturel et les grands enjeux qui nécessitent sa protection !\r\n\r\nRDV : Maison de la Réserve à Condamine (Saint-Victor-sur-Loire)\r\n\r\nSur inscription jusqu’au vendredi 14 h (de 4 à 10 places)\r\nAnimation annulée si moins de 4 inscrits.\r\n\r\nTarif : 2 €', '45.457562', '4.263197'),
(21, 'Visite guidée de la réserve naturelle des gorges de la Loire', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgjGWTaQrx7Vi2CMZIk4X9cU80rTanpEVbIyVTwVGKeMSv4FWPjw', '2019-02-10', '2019-02-10', '14 h 30 - 16 h 30', 'Stéphanois-Pilat', 'Réserve Naturelle Régionale des gorges de la Loire', 'null', 'Famille', 'Sorties découvertes', 'TRUE', 'https://loireenvert.fr/events/visite-guidee-de-reserve-naturelle-gorges-de-loire-2019-01-13/', 'Lors d’une balade commentée, venez découvrir un site naturel exceptionnel et protégé depuis 1988 sous la forme d’une réserve naturelle.\r\n\r\nSa mosaïque de milieux naturels et sa richesse faunistique et floristique sont protégés par la FRAPNA Loire et le SMAGL depuis 2012.\r\n\r\nAu départ de la Maison de la Réserve, votre guide vous emmènera aux deux points de vue les plus connus de la réserve, avec vue plongeante sur les gorges de la Loire !\r\n\r\nLaissez-vous raconter de manière interactive l’histoire du site, son patrimoine naturel et les grands enjeux qui nécessitent sa protection !\r\n\r\nRDV : Maison de la Réserve à Condamine (Saint-Victor-sur-Loire)\r\n\r\nSur inscription jusqu’au vendredi 14 h (de 4 à 10 places)\r\nAnimation annulée si moins de 4 inscrits.\r\n\r\nTarif : 2 €', '45.457562', '4.263197'),
(22, 'Visite guidée de la réserve naturelle des gorges de la Loire\r\n', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgjGWTaQrx7Vi2CMZIk4X9cU80rTanpEVbIyVTwVGKeMSv4FWPjw', '2019-03-10', '2019-03-10', '14 h 30 - 16 h 30', 'Stéphanois-Pilat', 'Réserve Naturelle Régionale des gorges de la Loire', 'null', 'Famille', 'Sorties découvertes', 'TRUE', 'https://loireenvert.fr/events/visite-guidee-de-reserve-naturelle-gorges-de-loire-2019-01-13/', 'Lors d’une balade commentée, venez découvrir un site naturel exceptionnel et protégé depuis 1988 sous la forme d’une réserve naturelle.\r\n\r\nSa mosaïque de milieux naturels et sa richesse faunistique et floristique sont protégés par la FRAPNA Loire et le SMAGL depuis 2012.\r\n\r\nAu départ de la Maison de la Réserve, votre guide vous emmènera aux deux points de vue les plus connus de la réserve, avec vue plongeante sur les gorges de la Loire !\r\n\r\nLaissez-vous raconter de manière interactive l’histoire du site, son patrimoine naturel et les grands enjeux qui nécessitent sa protection !\r\n\r\nRDV : Maison de la Réserve à Condamine (Saint-Victor-sur-Loire)\r\n\r\nSur inscription jusqu’au vendredi 14 h (de 4 à 10 places)\r\nAnimation annulée si moins de 4 inscrits.\r\n\r\nTarif : 2 €', '45.457562', '4.263197'),
(23, 'Visite guidée de la réserve naturelle des gorges de la Loire', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgjGWTaQrx7Vi2CMZIk4X9cU80rTanpEVbIyVTwVGKeMSv4FWPjw', '2019-04-14', '2019-04-14', '14 h 30 - 16 h 30', 'Stéphanois-Pilat', 'Réserve Naturelle Régionale des gorges de la Loire', 'null', 'Famille', 'Sorties découvertes', 'True', 'https://loireenvert.fr/events/visite-guidee-de-reserve-naturelle-gorges-de-loire-2019-04-14/', 'Lors d’une balade commentée, venez découvrir un site naturel exceptionnel et protégé depuis 1988 sous la forme d’une réserve naturelle.\r\n\r\nSa mosaïque de milieux naturels et sa richesse faunistique et floristique sont protégés par la FRAPNA Loire et le SMAGL depuis 2012.\r\n\r\nAu départ de la Maison de la Réserve, votre guide vous emmènera aux deux points de vue les plus connus de la réserve, avec vue plongeante sur les gorges de la Loire !\r\n\r\nLaissez-vous raconter de manière interactive l’histoire du site, son patrimoine naturel et les grands enjeux qui nécessitent sa protection !\r\n\r\nRDV : Maison de la Réserve à Condamine (Saint-Victor-sur-Loire)\r\n\r\nSur inscription jusqu’au vendredi 14 h (de 4 à 10 places)\r\nAnimation annulée si moins de 4 inscrits.\r\n\r\nTarif : 2 €', '45.457562', '4.263197'),
(24, 'Fête du sol et de la terre', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjo-YjoQbH0eoqv3lOE2K4TwDPWgIuymPIzApvWhVMPfDClkYq', '2019-03-17', '2019-03-17', '10 h 00 - 18 h 00\r\n', 'Forez', 'Ecopôle du Forez', 'null', 'Famille', 'Evénements', 'false', 'https://loireenvert.fr/events/fete-du-sol-terre/', 'Dans le cadre de la journée internationale de la forêt (21 mars), venez fêter avec nous un arbre commun des bords de Loire que nous utilisons tous sous différentes formes depuis des millénaires.\r\n\r\nProgramme\r\nTressage de saule vivant,\r\nInitiation à la vannerie,\r\nExpo-vente de maîtres vanniers,\r\nBalade nature,\r\nAteliers enfants,\r\nConstruction de nichoirs\r\n\r\nSans inscription\r\n\r\nTarif \r\n1€ par personne (adulte ou enfant)', '45.689464', '4.197532'),
(25, 'Spectacle de marionnettes animaux en danger et océan plastique', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfN3pXFBC_KkTUzXNRb3yb_aUUICzkE7vseaybnIYO4pljpR-nGQ', '2019-02-26', '2019-02-26', '14 h 30 - 15 h 15', 'Forez', 'Ecopôle du Forez', 'null', 'Enfants', 'Spectacle ', 'false', 'https://loireenvert.fr/events/spectacle-marionnettes/', 'Au cours d’un spectacle de marionnettes, il vous faudra aider les animaux de l’océan mis en danger à cause des très nombreux plastiques déposés par les Hommes.\r\nAvec le petit théâtre de lutine de Feurs.\r\n\r\nA partir de 4 ans\r\nSur inscription (de 5 à 25 places) jusqu’au 26 février 12 h.\r\nLes enfants doivent être accompagnés d’un adulte.\r\nTarif\r\n1 € par personne (adulte ou enfant)', '45.689464', '4.197532'),
(26, 'Voyage photographique', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIh3zGhnbJKfAEMPNTJ3Yulnq1kL8nDsdcGGA9CBER06bLI7bN', '2019-04-01', '2019-04-30', '13 h 30 - 18 h 00', 'Forez', 'Ecopôle du Forez', 'null', 'Public en situation de handicap', 'Expositions', 'false', 'https://loireenvert.fr/events/voyage-photographique-avril/', 'Pour s’émerveiller face à la beauté du monde, il n’est pas toujours utile de faire de longs voyages. À une heure de route, à deux pas de chez soi, il suffit parfois de changer de regard, de devenir curieux, de rester attentif. À travers ses images, Jessica BUCZEK vous invite à (re)découvrir les paysages naturels et les petites bêtes de la Loire, celles et ceux qui vous accompagnent au quotidien, sans que vous y prêtiez forcément attention ! Un voyage riche en couleurs et en émotion… À deux pas de chez soi !\r\n\r\nSans inscription\r\n\r\nOuverture :\r\n13 h 30 – 18 h\r\nMercredis, week-ends et jours fériés\r\nVacances scolaires : tous les jours\r\n\r\nTarif :\r\nPlein tarif : 3 €\r\nTarif réduit* : 1,60 €\r\n*Tarif réduit : demandeurs d’emploi, étudiants, enfants de 7 à 14 ans sur justificatif\r\nGratuit (sur justificatif) : enfants de moins de 7 ans, adhérents de la FNE Loire et de ses associations membres', '45.689464', '4.197532'),
(27, 'L’anniversaire d’Annie la fourmi', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIcHOJiKGU8diDNluv4r9J5qwC2QleDh_AuK5AJ78IXcMpyOi_0A', '2019-04-15', '2019-04-15', '14 h 30 - 16 h 00', 'Forez', 'Ecopôle du Forez', 'null', 'Enfants', 'Ateliers', 'false', 'https://loireenvert.fr/events/annie-la-fourmi-2019-04-15/', 'Pour les enfants : Viens aider l’équipe de l’Ecopôle à organiser l’anniversaire d’Annie la fourmi. Tu découvriras tous ses amis autour d’une fête surprise !\r\n\r\nA partir de 4 ans\r\n\r\nLes enfants doivent être accompagnés d’un adulte.\r\n\r\nSur inscription jusqu’au: 15 avril 12 h (de 5 à 15 places)\r\n\r\nMerci d’inscrire le nombre exact de participants (adultes et enfants)\r\nAnimation annulée si moins de 5 inscrits. Vous serez remboursé.\r\n\r\nTarif : \r\nAdulte : 5 €\r\nEnfant : 2,50 €', '45.689464', '4.197532'),
(28, 'L’anniversaire d’Annie la fourmi', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIcHOJiKGU8diDNluv4r9J5qwC2QleDh_AuK5AJ78IXcMpyOi_0A', '2019-04-16', '2019-04-16', '14 h 30 - 16 h 00', 'Forez', 'Ecopôle du Forez', 'null', 'Enfants', 'Ateliers', 'false', 'https://loireenvert.fr/events/annie-la-fourmi-2019-04-16/', 'Pour les enfants : Viens aider l’équipe de l’Ecopôle à organiser l’anniversaire d’Annie la fourmi. Tu découvriras tous ses amis autour d’une fête surprise !', '45.689464', '4.197532'),
(29, 'Trophée du Lignon forézien', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIh3zGhnbJKfAEMPNTJ3Yulnq1kL8nDsdcGGA9CBER06bLI7bN', '2019-05-18', '2019-05-18', '9 h 00 - 18 h 00', 'Forez', 'Stade de Poncins', 'null', 'Passionnés', 'Evénements', 'false', 'https://loireenvert.fr/events/trophee-du-lignon-forezien-2019/', 'Rencontre amicale de pêche à la mouche.\r\n\r\nTarif : 15 € pour les non-adhérents\r\n\r\nSur inscription\r\n\r\nRDV : Aire de loisir du pont du Lignon à Poncins', '45.733858', '4.158564'),
(30, 'Papillules, à la découverte du petit monde ailé', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqq6a9ysRitfrmH40zvMUKfkVS9oAuPm3S3IQe8lyj7MMuh7PF', '2019-06-05', '2019-06-05', '10 h 00 - 12 h 00', 'Forez', 'Ecopôle du Forez', 'Null', 'Passionnés', 'null', 'false', 'https://loireenvert.fr/events/papillules-a-la-decouverte-du-petit-monde-aile/', 'Nous vous invitons à découvrir libellules et papillons en bord de Loire : vulcain, tircis et tristan pour les papillons, caloptéryx, aeschnes et sympetrum pour les libellules. Notre accompagnateur-entomologiste passionné vous aidera à les trouver et à les identifier.\r\n\r\nSur inscription (de 5 à 20 places) jusqu’au 2 juin\r\nAnimation annulée si moins de 5 inscrits. Vous serez remboursé.', '45.689464', '4.197532'),
(31, 'La flore des zones humides\r\n', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-PiAdErWDr9Vi0y09-8c21UcEZVX1xr7pEzLCFpjsGDvDVCYh', '2019-06-30', '2019-06-30', '9 h 30 - 12 h 00', 'Forez', 'Ecopôle du Forez', 'null', 'Passionnés', 'Sorties découvertes', 'false', 'https://loireenvert.fr/events/la-flore-des-zones-humides/', 'Sortez des sentiers battus de l’Ecopôle du Forez pour découvrir, au coeur des marais de l’Ecozone, la richesse de la flore des zones humides des bords de Loire.\r\n\r\nSur inscription (de 5 à 15 places) jusqu’au 27 juin\r\nAnimation annulée si moins de 5 inscrits. Vous serez remboursé.\r\n\r\nPour un public de passionnés.', '45.689464', '4.197532'),
(32, 'La vie secrète de la mare', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRENa7iJQVYkOCZ4jiWvUfkTswq7Q5TyP9KDfPRzBlaQrMiXmRK', '2019-07-09', '2019-07-09', '14 h 30 - 16 h 00', 'Forez', 'Ecopôle du Forez', 'null', 'Famille', 'Ateliers', 'false', 'https://loireenvert.fr/events/la-vie-secrete-de-la-mare-2019-07-09-2/', 'Pour les enfants : épuisette et boîte loupe à la main, allons-nous installer au bord de la mare et capturer ses mystérieux habitants.\r\n\r\nA partir 4 ans\r\nLes enfants doivent être accompagnés d’un adulte. Les adultes doivent aussi s’inscrire.\r\n\r\nSur inscription jusqu’au : 8 juillet 12 h (de 5 à 15 places)\r\nAnimation annulée si moins de 5 inscrits. Vous serez remboursé.\r\n\r\nTarif\r\nAdultes : 5 €\r\nEnfants jusqu’à 14 ans : 2,50 €', '45.689464', '4.197532'),
(33, 'La vie secrète de la mare', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRENa7iJQVYkOCZ4jiWvUfkTswq7Q5TyP9KDfPRzBlaQrMiXmRK', '2019-07-10', '2019-07-10', '14 h 30 - 16 h 00', 'Forez', 'Ecopôle du Forez', 'null', 'Famille', 'Ateliers', 'false', 'https://loireenvert.fr/events/la-vie-secrete-de-la-mare-2019-07-10/', 'Pour les enfants : épuisette et boîte loupe à la main, allons-nous installer au bord de la mare et capturer ses mystérieux habitants.\r\n\r\nA partir 4 ans\r\nLes enfants doivent être accompagnés d’un adulte. Les adultes doivent aussi s’inscrire.\r\n\r\nSur inscription jusqu’au : 9 juillet 12 h (de 5 à 15 places)\r\nAnimation annulée si moins de 5 inscrits. Vous serez remboursé.\r\n\r\nTarif\r\nAdultes : 5 €\r\nEnfants jusqu’à 14 ans : 2,50 €', '45.689464', '4.197532'),
(34, 'A la découverte des abeilles', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBSpcjlJf2ungZlyAJaUQweFPo-tzRlqlRhb7ZXOTE4iOugz5l', '2019-01-29', '2019-01-29', '18 h 30 - 20 h 00', 'Stéphanois-Pilat', 'Maison de la Nature', 'Saint-Etienne', 'Passionnés', 'Apéro-quiz', 'true', 'https://loireenvert.fr/events/apero-quiz-decouverte-des-abeilles/', 'Conférence sous forme de quiz. Pour ceux et celles qui ont un smartphone, une tablette… répondez au quiz directement sur votre écran.\r\n\r\nVenez découvrir la vie des abeilles autour d’un Apéro-quiz en répondant aux questions suivantes (et bien d’autres) !\r\n– Combien y a-t-il d’habitants différents dans une ruche ?\r\n– Combien de métiers pratique une abeille au cours de sa vie ?\r\n– Comment les abeilles fabriquent-elles le miel ?\r\n– Pourquoi et comment sauver les abeilles ?\r\n\r\nAndré Héritier, apiculteur, vous emmène explorer le monde des abeilles et vous fera découvrir leur rôle dans la biodiversité.\r\n\r\nGratuit\r\nSur inscription avant 18 h (30 places)', '45.457562', '4.263197'),
(35, 'Des gorges ou d’ailleurs', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1in5dR3TEYIKPT_moY_IZnEcaovx8gvaVtf6y7_mxPTuTBB34nw', '2019-02-20', '2019-02-20', '14 h 00 - 16 h 00', 'Stéphanois-Pilat', 'Réserve Naturelle Régionale des gorges de la Loire', 'null', 'Famille', 'Sorties découvertes', 'false', 'https://loireenvert.fr/events/des-gorges-ou-d-ailleurs/', 'Recherche les silhouettes des habitants de la réserve naturelle en parcourant les sentiers forestiers et apprends à les connaître à travers un jeu de piste.\r\n\r\nDès 6 ans\r\nSur inscription (de 5 à 25 places) jusqu’au 20 février 12 h.\r\nLes enfants doivent être accompagnés d’un adulte.\r\n\r\nPrévoir : Vêtements adaptés à la météo.\r\nBalade de 1,5 à 2 km selon l’âge\r\n\r\nTarif\r\nAdultes accompagnant : 3 €\r\nEnfants (7-14 ans) : 2 €\r\nGratuit moins de 7 ans', '45.457562', '4.263197'),
(36, 'Apéro-quiz : l’eau dans la Loire', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPXEj4JsEZe4QjMyRfWuECxJ0OthDgLwwef49ZKgjqTbL4K_PR-w', '2019-03-20', '2019-03-20', '18 h 30 - 20 h 30', 'Stéphanois-Pilat', 'Maison de la Nature', 'Saint-Etienne', 'Passionnés', 'Apéro-quiz', 'true', 'https://loireenvert.fr/events/apero-quiz-eau-loire-2019/', 'Dans le cadre de la consultation du public sur l’eau (du 2 novembre 2018 au 2 mai 2019), FNE Loire organise pour vous un apéro-quiz à la Maison de la Nature sur les enjeux de l’eau dans le département de la Loire.\r\n\r\nVenez passer un moment convivial pendant lequel nous répondrons ensemble à ces questions et aux autres que vous pouvez vous poser.\r\n\r\nGratuit\r\n\r\nSur inscription (de 3 à 30 places) jusqu’au 12 mars.', '45.420986', '4.385753'),
(37, 'Le rendez-vous vert de la Cotonne', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMa4dGhIB09p6A2pv4568rXWDqBZwwE9OxZR2adGBCwUVZZiEH', '2019-03-13', '2019-03-13', '14 h 00 - 17 h 00', 'Stéphanois-Pilat', 'La Cotonne-Montferré', 'Saint-Etienne', 'Famille', 'Ateliers', 'true', 'https://loireenvert.fr/events/rendez-vous-vert-la-cotonne-mars/', 'Rendez-vous régulier pour profiter d’un moment convivial autour de la nature et de l’écocitoyenneté.\r\n\r\nRetrouvons-nous sur la place Bobby Sands (quartier de la Cotonne-Montferré) et baladons-nous jusqu’au jardin de la Maison de la nature pour des ateliers que Thomas et Julie seront ravis de partager avec vous :\r\n– jardinage,\r\n– recyclage,\r\n– compostage,\r\n– autres trucs et astuces\r\n\r\nEnfants bienvenus dès 7 ans \r\nLes moins de 15 ans doivent être accompagnés d’un adulte.\r\n\r\nSans inscription\r\nRDV :Devant la boulangerie de la Place Bobby Sands à Saint-Etienne\r\n\r\nGratuit', '45.420972', '4.384169');

--
-- Index pour les tables exportées
--

--
-- Index pour la table `eventLoire`
--
ALTER TABLE `eventLoire`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables exportées
--

--
-- AUTO_INCREMENT pour la table `eventLoire`
--
ALTER TABLE `eventLoire`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=38;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
